services:
  - type: web
    name: compilador
    env: docker
    plan: free
    dockerfile: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ANDROID_HOME
        value: /opt/android-sdk
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 10
