services:
  - type: web
    name: compilador
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 10
